# Generated by Django 5.2.6 on 2025-09-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('aqi', models.IntegerField()),
                ('aqi_category', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('unhealthy_sensitive', 'Unhealthy for Sensitive Groups'), ('unhealthy', 'Unhealthy'), ('very_unhealthy', 'Very Unhealthy'), ('hazardous', 'Hazardous')], max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_smoke_opacity', models.FloatField(help_text='Maximum allowed smoke opacity percentage')),
                ('max_pm25', models.FloatField(blank=True, null=True)),
                ('max_pm10', models.FloatField(blank=True, null=True)),
                ('max_no2', models.FloatField(blank=True, null=True)),
                ('max_co', models.FloatField(blank=True, null=True)),
                ('vehicle_types', models.JSONField(blank=True, default=list)),
                ('applicable_regions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.IntegerField(blank=True, null=True)),
                ('weather_condition', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=100)),
                ('cloud_coverage', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('measurement_date', models.DateField()),
                ('total_violations', models.IntegerField(default=0)),
                ('average_aqi', models.FloatField(blank=True, null=True)),
                ('pollution_reduction_percentage', models.FloatField(blank=True, null=True)),
                ('total_vehicles_detected', models.IntegerField(default=0)),
                ('compliant_vehicles', models.IntegerField(default=0)),
                ('violation_rate', models.FloatField(default=0.0)),
                ('air_quality_trend', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-measurement_date'],
                'unique_together': {('location', 'measurement_date')},
            },
        ),
    ]
